!include names.puml

frame "logic unit structure" {
interface "$uif" as uif
interface "$if" as if
component "$impl" <<unit>>  as impl
component "$user" <<unit>>  as user
}

uif -- user
user --> if
if -down- impl
